//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _i.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MicroAuto.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Beri {
            get {
                object obj = ResourceManager.GetObject("Beri", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon BeriIcon {
            get {
                object obj = ResourceManager.GetObject("BeriIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream chat {
            get {
                return ResourceManager.GetStream("chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream chatex {
            get {
                return ResourceManager.GetStream("chatex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Đèn nhà ai nấy sáng]-&gt;[Đại Lý-Triệu Thiên Sư][160,159-2]-&gt;[Đại Lý-Đoàn Chính Thuần][71,18-2]
        ///[Áo xanh lỗi lạc hành núi hiểm]-&gt;[Đại Lý-Đoàn Chính Thuần][71,18-2]-&gt;[Vạn Kiếp Cốc-Chung Linh][28,15-119]
        ///[Vi Tiếu Chi Lữ]-&gt;[Vạn Kiếp Cốc-Chung Linh][28,15-119]-&gt;[Vạn Kiếp Cốc-Vạn Kiếp Cốc Thạch Cảm Đương][48,95-119]
        ///[Ác Quán Mãn Doanh]-&gt;[Vạn Kiếp Cốc-Vạn Kiếp Cốc Thạch Cảm Đương][48,95-119]-&gt;[Đại Lý-Đoàn Chính Thuần][71,18-2]
        ///[Gặp nhau tại Vạn Kiếp Cốc]-&gt;[Đại Lý-Đoàn Chính Thuần][71,18-2]-&gt;[Vạn Kiếp Cốc-Đoàn C [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ChinhTuyen {
            get {
                return ResourceManager.GetString("ChinhTuyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap exp {
            get {
                object obj = ResourceManager.GetObject("exp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function Quest_Open()
        ///	this:Show();
        ///	
        ///	NpcName = Target:GetDialogNpcName();
        ///	MapID = GetSceneID();
        ///	
        ///	if string.find(NpcName, &apos;Mô Kim Hi®u Úy&apos;) then 
        ///		QuestFrameOptionClicked(-1, 50063, 100); 
        ///	end
        ///	
        ///	if string.find(NpcName, &apos;Ác T£c TÕo Phän&apos;) then
        ///	   if MapID == 3 then
        ///			QuestFrameOptionClicked(-1, 50013, -1);
        ///		elseif MapID == 4 then
        ///			QuestFrameOptionClicked(-1, 50013, -1);
        ///		elseif MapID == 5 then
        ///			QuestFrameOptionClicked(-1, 50013, -1);
        ///		elseif MapID == 6 then
        ///			QuestFrameOpti [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Fix2D {
            get {
                return ResourceManager.GetString("Fix2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function Quest_Open()
        ///	this:Show();
        ///	
        ///	if(IsWindowShow(&apos;ChangyigeZigeCheck&apos;)) then
        ///		 CloseWindow(&apos;ChangyigeZigeCheck&apos;, true)
        ///	end
        ///	
        ///	NpcName = Target:GetDialogNpcName();
        ///	MapID = GetSceneID();
        ///	
        ///	if string.find(NpcName, &apos;Mô Kim Hi®u Úy&apos;) then 
        ///		QuestFrameOptionClicked(-1, 50063, 100); 
        ///	end
        ///	
        ///	if string.find(NpcName, &apos;Ác T£c TÕo Phän&apos;) then
        ///	   if MapID == 3 then
        ///			QuestFrameOptionClicked(-1, 50013, -1);
        ///		elseif MapID == 4 then
        ///			QuestFrameOptionClicked(-1, 50013, -1);
        ///		elseif MapID [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Fix3D {
            get {
                return ResourceManager.GetString("Fix3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function Quest_Open()
        ///	this:Show();
        ///	
        ///	NpcName = Target:GetDialogNpcName();
        ///	MapID = GetSceneID();
        ///	
        ///	if string.find(NpcName, &apos;Mô Kim Hi®u Úy&apos;) then 
        ///		QuestFrameOptionClicked(-1, 50063, 100); 
        ///	end
        ///	
        ///	if string.find(NpcName, &apos;Ác T£c TÕo Phän&apos;) then
        ///	   if MapID == 3 then
        ///			QuestFrameOptionClicked(-1, 50013, -1);
        ///		elseif MapID == 4 then
        ///			QuestFrameOptionClicked(-1, 50013, -1);
        ///		elseif MapID == 5 then
        ///			QuestFrameOptionClicked(-1, 50013, -1);
        ///		elseif MapID == 6 then
        ///			QuestFrameOpti [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FixDG {
            get {
                return ResourceManager.GetString("FixDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hp {
            get {
                object obj = ResourceManager.GetObject("hp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function AppointLeader(name)
        ///
        ///	local count = DataPool:GetTeamMemberCount();
        ///	
        ///	local szNick;
        ///	local iFamily;
        ///	local iLevel;
        ///	local bDeadlink;
        ///	local bDead;
        ///	local bSex;
        ///    local sZoneWorldID
        ///	
        ///	for i = 0, count - 1 do
        ///		szNick
        ///		,iFamily
        ///		,iLevel
        ///		,bDead
        ///		,bDeadlink
        ///		,bSex
        ///		,sZoneWorldID
        ///		= DataPool:GetTeamMemInfoByIndex(i);
        ///		if szNick == name then
        ///			Player:AppointLeader(i);
        ///			break;
        ///		end
        ///	end
        ///	
        ///end
        ///
        ///function XuatPet(id)
        ///	for i = 1, 10 do 
        ///		if Pet:IsPresent(i-1)  t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Lua {
            get {
                return ResourceManager.GetString("Lua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MISSION = &quot;&quot;;
        ///for iMissionType = 1, 200 do
        ///	local DeployNum = GetMissionOutlineNum(iMissionType);
        ///	local nMyLevel = Player:GetData(&quot;LEVEL&quot;);
        ///	for i=1, DeployNum do
        ///		local MissionLevel, MinLevel, MaxLevel, strNpcName, strNpcPos, strScene, strMissionName, PosX, PosY, SceneID = GetMissionOutlineInfo(iMissionType, i);		
        ///		if(MissionLevel &lt;= nMyLevel and MissionLevel ~= nil and strMissionName ~= nil) then
        ///			local strInfo = &quot;&quot;;
        ///			strNpcPos = &quot;#{_INFOAIM&quot;..(PosX)..&quot;,&quot;..(PosY)..&quot;,&quot;..(SceneID)..&quot;,&quot;..(strN [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LuaEx {
            get {
                return ResourceManager.GetString("LuaEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap map {
            get {
                object obj = ResourceManager.GetObject("map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MAP]
        ///153=13,29-32,34-48,34-32,20-40,18
        ///13=105,108-130,117-145,151-159,157-159,140-121,70-78,60-44,41
        ///16=83,132-50,134-69,107-48,86-65,99-94,95-109,117-145,93
        ///14=147,116-146,146-97,125-68,56-53,88-49,159-97,125-145,58
        ///9=118,107-137,136-135,79-90,74-69,64-66,108-67,146-94,108
        ///17=94,118-68,93-47,138-47,74-130,52-118,98-133,76-143,136
        ///15=96,83-57,142-36,108-45,41-94,37-142,106-146,153-146,46
        ///12=71,176-46,179-45,136-103,108-75,79-43,86-48,55-88,51
        ///11=115,139-156,143-153,113-93,50-56,41-41,87-41,153-80, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string mapini {
            get {
                return ResourceManager.GetString("mapini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mid {
            get {
                object obj = ResourceManager.GetObject("mid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mp {
            get {
                object obj = ResourceManager.GetObject("mp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon paused {
            get {
                object obj = ResourceManager.GetObject("paused", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream pm {
            get {
                return ResourceManager.GetStream("pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Publishers&gt;
        ///  &lt;Publisher Name=&quot;VinaGame&quot; Path=&quot;&quot;&gt;
        ///    &lt;Servers&gt;
        ///      &lt;Server&gt;Thiên Long 15&lt;/Server&gt;
        ///      &lt;Server&gt;Bạch Hổ&lt;/Server&gt;
        ///      &lt;Server&gt;Thánh Hỏa&lt;/Server&gt;
        ///      &lt;Server&gt;Huyền Tố&lt;/Server&gt;      
        ///      &lt;Server&gt;Thanh Long&lt;/Server&gt;
        ///      &lt;Server&gt;Thiên Long 01&lt;/Server&gt;
        ///      &lt;Server&gt;Thiên Long 11&lt;/Server&gt;
        ///      &lt;Server&gt;Thiên Long 14&lt;/Server&gt;
        ///      &lt;Server&gt;Thiên Long 16&lt;/Server&gt;
        ///      &lt;Server&gt;Thiên Long 17&lt;/Server&gt;
        ///      &lt;Server&gt;Thiên Long 18&lt;/Server&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Publishers {
            get {
                return ResourceManager.GetString("Publishers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sound {
            get {
                object obj = ResourceManager.GetObject("sound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
