//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroAuto.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Panel1")]
        public global::System.Windows.Forms.FixedPanel Fixed {
            get {
                return ((global::System.Windows.Forms.FixedPanel)(this["Fixed"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Cô Tô Mộ Dung
Hoàn Thị Thủy Các
Độc chiến song hùng
Đêm dài lắm mộng
Nhất phẩm đường
Chỉ Điểm Quần Hào
Bi Tô Thanh Phong
Tứ hải là nhà
Quần Long Vô Thủ
Cùng Tiến Cùng Lùi
Thiên hạ võ công xuất Thiếu Lâm
Tụ Hiền Trang
Đỉnh thiên lập địa
Kỳ sau gặp mặt
Dù vạn người, ta vẫn cứ tiến
Huyết Chiến Tụ Hiền Trang
Bảo vệ Mã Phu Nhân
Nhất Bàn Tản Sa
Tới núi Thương Mang
Thiên thời không bằng địa lợi
Cần Vương
Bày mưu tính kế
Tứ Diện Sở Ca
Kim Qua Đãng Khấu Ngao Binh
Lục Quân Tị Dịch
Trân Long Kỳ Hội
Tịnh hầu quế âm
Thua thắng thành bại ai biết được
Chọn ngày tái chiến
Đóng cửa bắt trộm
Hội Thi Túc Cầu
Nhất kiếm thượng thiên sơn
Dù nguy mà yên
Y tiếu nhân gian vạn sự
Cái Bang Nghi Vấn Ban Đầu
Trừ độc vật giải nguy Cái Bang
Cùng tiến lên Thiếu Lâm")]
        public string ChínhTuyến {
            get {
                return ((string)(this["ChínhTuyến"]));
            }
            set {
                this["ChínhTuyến"] = value;
            }
        }
    }
}
